### ISSUE TITLE
tuned-gui: trying to concat str and list, when reading radeon_powersave options

### ISSUE THREAD

**Issue by evgeni** [redhat-performance/tuned#123]
via [Debian bug #900858](https://bugs.debian.org/900858):

```
Traceback (most recent call last):
  File "/usr/sbin/tuned-gui", line 1037, in <module>
    base = Base()
  File "/usr/sbin/tuned-gui", line 325, in __init__
    self.data_for_listbox_summary_of_active_profile()
  File "/usr/sbin/tuned-gui", line 505, in data_for_listbox_summary_of_active_profile
    + '</b>')
TypeError: cannot concatenate 'str' and 'list' objects
```

seems that options are sometimes a `list`?

**Comment by olysonek** [comment]
Try applying https://github.com/redhat-performance/tuned/commit/c37b6220d4bca.
