### ISSUE TITLE
tuned-gui fails to start with :AttributeError: module 'perf' has no attribute 'cpu_map'

### ISSUE THREAD

**Issue by Maryse47** [redhat-performance/tuned#149]
tuned-gui fails to start with the following log:

```
Traceback (most recent call last):
  File "/usr/sbin/tuned-gui", line 1035, in <module>
    base = Base()
  File "/usr/sbin/tuned-gui", line 150, in __init__
    tuned.gtk.gui_plugin_loader.GuiPluginLoader()
  File "/usr/lib/python3.7/site-packages/tuned/gtk/gui_plugin_loader.py", line 87, in __init__
    self.create_all(self._import_plugin_names())
  File "/usr/lib/python3.7/site-packages/tuned/gtk/gui_plugin_loader.py", line 119, in create_all
    self._plugins.add(self.repo.create(plugin_name))
  File "/usr/lib/python3.7/site-packages/tuned/plugins/repository.py", line 36, in create
    self._device_matcher_udev, self._plugin_instance_factory, self._global_cfg, self._variables)
  File "/usr/lib/python3.7/site-packages/tuned/plugins/plugin_scheduler.py", line 75, in __init__
    self._cpus = perf.cpu_map()
AttributeError: module 'perf' has no attribute 'cpu_map'
```

It happens on ArchLinux with package built from: The package was build from https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tuned-git

**Comment by hifi25nl** [comment]
I confirm the same error here on Archlinux

**Comment by yarda** [comment]
@hifi25nl it looks like error in Arch packaging, it seems the Arch package requires this package: https://github.com/vstinner/perf, but Tuned needs Linux kernel perf, i.e. this one: https://perf.wiki.kernel.org/index.php/Main_Page

**Comment by yarda** [comment]
The perf which Tuned needs is part of the kernel sources, i.e.:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/tools/perf

**Comment by yarda** [comment]
I am closing this bug, the problem should be addressed in the Arch Linux, i.e. the 'depends' line should require the correct perf (i.e. the kernel perf).

**Comment by Maryse47** [comment]
Indeed, instaling `perf` fixed this issue. Thx for help!
