### ISSUE TITLE
`make test` fails

### ISSUE THREAD

**Issue by evgeni** [redhat-performance/tuned#35]
Ohai,

it seems that the tests currently fail all over the place (tested on Debian sid and Fedora 25):

```
# make test
python -m unittest discover tests
.........E..F.F.................E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E........
======================================================================
ERROR: units.test_device_matcher (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: units.test_device_matcher
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/tuned/tests/units/test_device_matcher.py", line 2, in <module>
    from tuned.units.device_matcher import DeviceMatcher
ImportError: No module named device_matcher


======================================================================
ERROR: test_default_load (profiles.test_loader.LoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_loader.py", line 30, in setUp
    self.loader = Loader(self._tmp_load_dirs, self.factory, self.merger)
TypeError: __init__() takes exactly 6 arguments (4 given)

======================================================================
ERROR: test_include_directive (profiles.test_loader.LoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_loader.py", line 30, in setUp
    self.loader = Loader(self._tmp_load_dirs, self.factory, self.merger)
TypeError: __init__() takes exactly 6 arguments (4 given)

======================================================================
ERROR: test_init (profiles.test_loader.LoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_loader.py", line 30, in setUp
    self.loader = Loader(self._tmp_load_dirs, self.factory, self.merger)
TypeError: __init__() takes exactly 6 arguments (4 given)

======================================================================
ERROR: test_init_wrong_type (profiles.test_loader.LoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_loader.py", line 30, in setUp
    self.loader = Loader(self._tmp_load_dirs, self.factory, self.merger)
TypeError: __init__() takes exactly 6 arguments (4 given)

======================================================================
ERROR: test_load (profiles.test_loader.LoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_loader.py", line 30, in setUp
    self.loader = Loader(self._tmp_load_dirs, self.factory, self.merger)
TypeError: __init__() takes exactly 6 arguments (4 given)

======================================================================
ERROR: test_load_empty (profiles.test_loader.LoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_loader.py", line 30, in setUp
    self.loader = Loader(self._tmp_load_dirs, self.factory, self.merger)
TypeError: __init__() takes exactly 6 arguments (4 given)

======================================================================
ERROR: test_load_invalid (profiles.test_loader.LoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_loader.py", line 30, in setUp
    self.loader = Loader(self._tmp_load_dirs, self.factory, self.merger)
TypeError: __init__() takes exactly 6 arguments (4 given)

======================================================================
ERROR: test_load_multiple_profiles (profiles.test_loader.LoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_loader.py", line 30, in setUp
    self.loader = Loader(self._tmp_load_dirs, self.factory, self.merger)
TypeError: __init__() takes exactly 6 arguments (4 given)

======================================================================
ERROR: test_load_nonexistent (profiles.test_loader.LoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_loader.py", line 30, in setUp
    self.loader = Loader(self._tmp_load_dirs, self.factory, self.merger)
TypeError: __init__() takes exactly 6 arguments (4 given)

======================================================================
ERROR: test_load_order (profiles.test_loader.LoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_loader.py", line 30, in setUp
    self.loader = Loader(self._tmp_load_dirs, self.factory, self.merger)
TypeError: __init__() takes exactly 6 arguments (4 given)

======================================================================
ERROR: test_script_expand_names (profiles.test_loader.LoaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_loader.py", line 30, in setUp
    self.loader = Loader(self._tmp_load_dirs, self.factory, self.merger)
TypeError: __init__() takes exactly 6 arguments (4 given)

======================================================================
ERROR: test_merge_multiple_order (profiles.test_merger.MergerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_merger.py", line 45, in test_merge_multiple_order
    config = merger.merge([config1, config2, config3])
  File "tuned/profiles/merger.py", line 16, in merge
    merged_config = reduce(self._merge_two, configs)
  File "tuned/profiles/merger.py", line 26, in _merge_two
    profile_a.options.update(profile_b.options)
AttributeError: 'OrderedDict' object has no attribute 'options'

======================================================================
ERROR: test_merge_with_replace (profiles.test_merger.MergerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_merger.py", line 33, in test_merge_with_replace
    config = merger.merge([config1, config2])
  File "tuned/profiles/merger.py", line 16, in merge
    merged_config = reduce(self._merge_two, configs)
  File "tuned/profiles/merger.py", line 26, in _merge_two
    profile_a.options.update(profile_b.options)
AttributeError: 'OrderedDict' object has no attribute 'options'

======================================================================
ERROR: test_merge_without_replace (profiles.test_merger.MergerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_merger.py", line 16, in test_merge_without_replace
    config = merger.merge([config1, config2])
  File "tuned/profiles/merger.py", line 16, in merge
    merged_config = reduce(self._merge_two, configs)
  File "tuned/profiles/merger.py", line 26, in _merge_two
    profile_a.options.update(profile_b.options)
AttributeError: 'OrderedDict' object has no attribute 'options'

======================================================================
ERROR: test_class_properties (plugins.test_base.PluginBaseClassTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/plugins/test_base.py", line 46, in setUp
    self.plugin = MockPlugin(self.monitor_repository, self.storage_factory)
TypeError: __init__() takes exactly 9 arguments (3 given)

======================================================================
ERROR: test_classs_with_invalid_commands (plugins.test_base.PluginBaseClassTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/plugins/test_base.py", line 46, in setUp
    self.plugin = MockPlugin(self.monitor_repository, self.storage_factory)
TypeError: __init__() takes exactly 9 arguments (3 given)

======================================================================
ERROR: test_cleanup (plugins.test_base.PluginBaseClassTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/plugins/test_base.py", line 46, in setUp
    self.plugin = MockPlugin(self.monitor_repository, self.storage_factory)
TypeError: __init__() takes exactly 9 arguments (3 given)

======================================================================
ERROR: test_exception_with_per_device_commands_when_no_devices_specified (plugins.test_base.PluginBaseClassTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/plugins/test_base.py", line 46, in setUp
    self.plugin = MockPlugin(self.monitor_repository, self.storage_factory)
TypeError: __init__() takes exactly 9 arguments (3 given)

======================================================================
ERROR: test_init (plugins.test_base.PluginBaseClassTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/plugins/test_base.py", line 46, in setUp
    self.plugin = MockPlugin(self.monitor_repository, self.storage_factory)
TypeError: __init__() takes exactly 9 arguments (3 given)

======================================================================
ERROR: test_instance_properties (plugins.test_base.PluginBaseClassTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/plugins/test_base.py", line 46, in setUp
    self.plugin = MockPlugin(self.monitor_repository, self.storage_factory)
TypeError: __init__() takes exactly 9 arguments (3 given)

======================================================================
ERROR: test_merge_known_options (plugins.test_base.PluginBaseClassTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/plugins/test_base.py", line 46, in setUp
    self.plugin = MockPlugin(self.monitor_repository, self.storage_factory)
TypeError: __init__() takes exactly 9 arguments (3 given)

======================================================================
ERROR: test_merge_unknown_options (plugins.test_base.PluginBaseClassTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/plugins/test_base.py", line 46, in setUp
    self.plugin = MockPlugin(self.monitor_repository, self.storage_factory)
TypeError: __init__() takes exactly 9 arguments (3 given)

======================================================================
ERROR: test_storage_with_device_independent_commands (plugins.test_base.PluginBaseClassTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/plugins/test_base.py", line 46, in setUp
    self.plugin = MockPlugin(self.monitor_repository, self.storage_factory)
TypeError: __init__() takes exactly 9 arguments (3 given)

======================================================================
ERROR: test_storage_with_per_device_commands (plugins.test_base.PluginBaseClassTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/plugins/test_base.py", line 46, in setUp
    self.plugin = MockPlugin(self.monitor_repository, self.storage_factory)
TypeError: __init__() takes exactly 9 arguments (3 given)

======================================================================
ERROR: test_update_tuning_not_implemented (plugins.test_base.PluginBaseClassTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/plugins/test_base.py", line 46, in setUp
    self.plugin = MockPlugin(self.monitor_repository, self.storage_factory)
TypeError: __init__() takes exactly 9 arguments (3 given)

======================================================================
FAIL: test_create_units (profiles.test_profile.ProfileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_profile.py", line 20, in test_create_units
    self.assertIs(type(profile.units), list)
AssertionError: <class 'collections.OrderedDict'> is not <type 'list'>

======================================================================
FAIL: test_create_units_empty (profiles.test_profile.ProfileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tuned/tests/profiles/test_profile.py", line 27, in test_create_units_empty
    self.assertIs(type(profile.units), list)
AssertionError: <class 'collections.OrderedDict'> is not <type 'list'>

----------------------------------------------------------------------
Ran 61 tests in 0.014s

FAILED (failures=2, errors=26)
```

This happens in both, master and on the latest release tag (v2.7.1).

**Comment by yarda** [comment]
Yes, we know, the unit tests are in very bad state. We are going to improve it, also patches or volunteers are welcome :)
But the project is not without test suite, we have internal CI with regression tests, unfortunately we cannot opensource it at the moment due to some licensing problems, but we are working on it.

**Comment by evgeni** [comment]
Seems they started failing at 4e57882366e3afe217e9d93beeda897c6818f63c

**Comment by olysonek** [comment]
The tests now pass, at least on Fedora, thanks to @TomasKorbar :)
