### ISSUE TITLE
ERRORS

### ISSUE THREAD

**Issue by mizzunet** [redhat-performance/tuned#424]
I'm having the following errors. 
`laptop-battery-powersave`
```
󰅂 doas tuned
...
...
2022-03-17 21:54:06,996 WARNING  tuned.plugins.plugin_cpu: unable to run x86_energy_perf_policy tool, ignoring CPU energy performance bias, is the tool installed?
2022-03-17 21:54:07,114 ERROR    tuned.utils.commands: Error when reading file '/sys/class/drm/card0/device/power_method': '[Errno 2] No such file or directory: '/sys/class/drm/card0/device/power_method''
2022-03-17 21:54:07,115 WARNING  tuned.plugins.plugin_video: radeon_powersave is not supported on 'card0'
2022-03-17 21:54:07,116 ERROR    tuned.units.manager: BUG: Unhandled exception in start_tuning: name 'args' is not defined
2022-03-17 21:54:07,116 ERROR    tuned.units.manager: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/tuned/units/manager.py", line 119, in _try_call
    return f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/tuned/plugins/instance/instance.py", line 78, in apply_tuning
    self._plugin.instance_apply_tuning(self)
  File "/usr/lib/python3.10/site-packages/tuned/plugins/base.py", line 266, in instance_apply_tuning
    self._run_for_each_device(instance, self._instance_apply_dynamic, instance.assigned_devices)
  File "/usr/lib/python3.10/site-packages/tuned/plugins/base.py", line 207, in _run_for_each_device
    callback(instance, device)
  File "/usr/lib/python3.10/site-packages/tuned/plugins/plugin_disk.py", line 251, in _instance_apply_dynamic
    super(DiskPlugin, self)._instance_apply_dynamic(*args, **kwargs)
NameError: name 'args' is not defined

2022-03-17 21:54:07,141 ERROR    tuned.plugins.plugin_script: script '/usr/lib/tuned/powersave/script.sh' error output: 'wlan0     no private ioctls.
'
...
...
```

Info:
OS: Artix
Init: OpenRC
Processor: Intel i5-4th 

`ls /sys/class/drm/card0/device`
```
 driver                      i2c-4      ari_enabled                device            modalias      reset_method   rom
 drm                         i2c-5      boot_vga                   dma_mask_bits     msi_bus       resource       subsystem_device
 firmware_node               i2c-6      broken_parity_status       driver_override   numa_node     resource0      subsystem_vendor
 graphics                    link       class                      enable            power_state   resource2      uevent
 i2c-1                       msi_irqs   config                     irq               remove        resource2_wc   vendor
 i2c-2                       power      consistent_dma_mask_bits   local_cpulist     rescan        resource4
```

**Comment by yarda** [comment]
Maybe it also shouldn't write this error:
```
ERROR    tuned.utils.commands: Error when reading file '/sys/class/drm/card0/device/power_method': '[Errno 2] No such file or directory: '/sys/class/drm/card0/device/power_method''
```
Because it's covered by the next warning which says that the radeon_powersave is not supported on 'card0'. @CZerta I think the code could be improved not to write the error.

Also the TuneD profile laptop-battery-powersave is kept for backward compatibility and it will be probably dropped in the feature. It's better to use the 'powersave' profile. In fact at the moment the laptop-battery-powersave profile is just wrapper (alias) to the powersave profile:
```
[main]
summary=Optimize laptop profile with more aggressive power saving
include=powersave
```

**Comment by mizzunet** [comment]
>  In fact at the moment the laptop-battery-powersave profile is just wrapper 

I tried `powersave` profile, now it does print `ERROR    tuned.utils.commands: Error ...`

**Comment by mizzunet** [comment]
Oops, I'm sorry, I meant " it does NOT print `ERROR tuned.utils.commands: Error ...`". 

Missed not

**Comment by loganmc10** [comment]
I am running into this same issue, here are the logs:
```
2022-06-14 16:17:46,976 INFO     tuned.daemon.application: TuneD: 2.18.0, kernel: 5.17.9-300.fc36.x86_64
2022-06-14 16:17:46,976 INFO     tuned.daemon.application: dynamic tuning is enabled (can be overridden in plugins)
2022-06-14 16:17:46,978 INFO     tuned.daemon.daemon: using sleep interval of 1 second(s)
2022-06-14 16:17:46,978 INFO     tuned.daemon.daemon: dynamic tuning is enabled (can be overridden by plugins)
2022-06-14 16:17:46,978 INFO     tuned.daemon.daemon: using update interval of 10 second(s) (10 times of the sleep interval)
2022-06-14 16:17:46,978 INFO     tuned.profiles.loader: loading profile: network-throughput
2022-06-14 16:17:46,982 INFO     tuned.daemon.controller: starting controller
2022-06-14 16:17:46,983 INFO     tuned.daemon.daemon: starting tuning
2022-06-14 16:17:46,986 INFO     tuned.plugins.base: instance cpu: assigning devices cpu3, cpu0, cpu1, cpu2
2022-06-14 16:17:46,987 INFO     tuned.plugins.plugin_cpu: We are running on an x86 GenuineIntel platform
2022-06-14 16:17:46,988 INFO     tuned.plugins.plugin_cpu: intel_pstate detected
2022-06-14 16:17:46,991 INFO     tuned.plugins.base: instance disk: assigning devices sda
2022-06-14 16:17:46,992 INFO     tuned.plugins.plugin_cpu: setting governor 'performance' on cpu 'cpu3'
2022-06-14 16:17:46,997 INFO     tuned.plugins.plugin_cpu: setting governor 'performance' on cpu 'cpu0'
2022-06-14 16:17:47,005 INFO     tuned.plugins.plugin_cpu: setting governor 'performance' on cpu 'cpu1'
2022-06-14 16:17:47,031 INFO     tuned.plugins.plugin_cpu: setting governor 'performance' on cpu 'cpu2'
2022-06-14 16:17:47,042 INFO     tuned.plugins.plugin_cpu: energy_perf_bias successfully set to 'performance' on cpu 'cpu3'
2022-06-14 16:17:47,044 INFO     tuned.plugins.plugin_cpu: energy_perf_bias successfully set to 'performance' on cpu 'cpu0'
2022-06-14 16:17:47,047 INFO     tuned.plugins.plugin_cpu: energy_perf_bias successfully set to 'performance' on cpu 'cpu1'
2022-06-14 16:17:47,049 INFO     tuned.plugins.plugin_cpu: energy_perf_bias successfully set to 'performance' on cpu 'cpu2'
2022-06-14 16:17:47,049 INFO     tuned.plugins.plugin_cpu: setting new cpu latency 1000
2022-06-14 16:17:47,050 ERROR    tuned.units.manager: BUG: Unhandled exception in start_tuning: name 'args' is not defined
2022-06-14 16:17:47,050 ERROR    tuned.units.manager: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/tuned/units/manager.py", line 119, in _try_call
    return f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/tuned/plugins/instance/instance.py", line 78, in apply_tuning
    self._plugin.instance_apply_tuning(self)
  File "/usr/lib/python3.10/site-packages/tuned/plugins/base.py", line 266, in instance_apply_tuning
    self._run_for_each_device(instance, self._instance_apply_dynamic, instance.assigned_devices)
  File "/usr/lib/python3.10/site-packages/tuned/plugins/base.py", line 207, in _run_for_each_device
    callback(instance, device)
  File "/usr/lib/python3.10/site-packages/tuned/plugins/plugin_disk.py", line 251, in _instance_apply_dynamic
    super(DiskPlugin, self)._instance_apply_dynamic(*args, **kwargs)
NameError: name 'args' is not defined

2022-06-14 16:17:47,050 INFO     tuned.plugins.plugin_sysctl: reapplying system sysctl
2022-06-14 16:17:47,051 INFO     tuned.daemon.daemon: static tuning from profile 'network-throughput' applied
```

OS is Fedora 36

**Comment by loganmc10** [comment]
I'm actually running TuneD in a container and I don't have a very good dev environment setup for it. I just pinged you since I saw you had written a fix for this issue, it seems like a pretty straight forward fix
