### ISSUE TITLE
OpenRC support

### ISSUE THREAD

**Issue by mizzunet** [redhat-performance/tuned#427]
Here's openrc service file: https://0x0.st/oNfI.txt
The service file is to be at `/etc/init.d/`

I don't know what to change  in`Makefile` to detect init and install service file accordingly. Else, I'd have made a PR.

And  `tuned-gui` fails to start

```
Traceback (most recent call last):
  File "/usr/bin/tuned-gui", line 902, in <module>
    base = Base()
  File "/usr/bin/tuned-gui", line 177, in __init__
    self.service_run_on_start_up('tuned'))
  File "/usr/bin/tuned-gui", line 729, in service_run_on_start_up
    temp = self._execute(['systemctl', 'is-enabled', service, '-q'])
  File "/usr/bin/tuned-gui", line 869, in _execute
    rc = subprocess.call(args)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'systemctl'
```

**Comment by yarda** [comment]
Definitely +1 from me, I am long time Gentoo / openrc user.

**Comment by Animeshz** [comment]
Also runit, I'm void/runit user.

**Comment by yarda** [comment]
Regarding the OpenRC support, TuneD service plugin already has support for OpenRC, i.e. it can start/stop/enable/disable OpenRC services. Now we need tuned and tuned-ppd OpenRC services which should be easy to add.

**Comment by yarda** [comment]
Regarding the other systems, unfortunately, I am not familiar with them, but I am ready to accept related PRs.
