### ISSUE TITLE
tuned-gui: tuned.admin.exceptions.TunedAdminDBusException: DBus call to TuneD daemon failed

### ISSUE THREAD

**Issue by vt-alt** [redhat-performance/tuned#668]
```
小马:~$ /usr/sbin/tuned-gui
Traceback (most recent call last):
  File "/usr/lib/python3/site-packages/tuned/admin/dbus_controller.py", line 79, in _call
    return method(*args, timeout=40)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: TypeError: 'bool' object is not iterable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/tuned-gui", line 968, in <module>
    base = Base()
           ^^^^^^
  File "/usr/sbin/tuned-gui", line 135, in __init__
    self.plugin_loader = tuned.gtk.gui_plugin_loader.GuiPluginLoader()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/tuned/gtk/gui_plugin_loader.py", line 58, in __init__
    self._get_plugins()
  File "/usr/lib/python3/site-packages/tuned/gtk/gui_plugin_loader.py", line 65, in _get_plugins
    self._plugins = self._dbus_controller.get_plugins()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/tuned/admin/dbus_controller.py", line 149, in get_plugins
    return self._call("get_all_plugins")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/tuned/admin/dbus_controller.py", line 84, in _call
    raise TunedAdminDBusException(err_str)
tuned.admin.exceptions.TunedAdminDBusException: DBus call to TuneD daemon failed
```
At the same time `systemctl status tuned` reports:
```
авг 08 23:59:07 pony.office systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
авг 08 23:59:07 pony.office systemd[1]: Started tuned.service - Dynamic System Tuning Daemon.
авг 08 23:59:21 pony.office tuned[2050043]: 2024-08-08 23:59:21,919 ERROR    dbus.service: Unable to append (False,) to message with signature a{sa{ss}}: <class 'TypeError'>: 'bool' object is not iterable
авг 08 23:59:21 pony.office tuned[2050043]: ERROR:dbus.service:Unable to append (False,) to message with signature a{sa{ss}}: <class 'TypeError'>: 'bool' object is not iterable
```

What this could be?

**Comment by vt-alt** [comment]
This is when run under user. When tuned-gui run under root there is no problem. 🤷

**Comment by vt-alt** [comment]
The user is in `wheel` group and the group is included in `addAdminRule`.
```
小马:~$ /usr/sbin/tuned-adm list plugins
DBus call to TuneD daemon failed
Not supported in no_daemon mode.
```
At the same time:
```
# journalctl -f
Aug 14 05:31:48 pony.office.basealt.ru tuned[3931197]: INFO:tuned.exports.dbus_exporter:action 'com.redhat.tuned.get_all_plugins' requested by caller ':1.94860' wasn't authorized, ignoring the request
Aug 14 05:31:48 pony.office.basealt.ru tuned[3931197]: 2024-08-14 05:31:48,166 ERROR    dbus.service: Unable to append (False,) to message with signature a{sa{ss}}: <class 'TypeError'>: 'bool' object is not iterable
Aug 14 05:31:48 pony.office.basealt.ru tuned[3931197]: ERROR:dbus.service:Unable to append (False,) to message with signature a{sa{ss}}: <class 'TypeError'>: 'bool' object is not iterable
```
I understand it's not getting `auth_admin` polkit permission, is it normal?

**Comment by vt-alt** [comment]
This should work locally due to `<allow_active>yes</allow_active>` this only gets extremely confusing in remote sessions.
